// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF4ymvTdp7B8Mq3J62i36dKsFgdlM2cpA',
    appId: '1:909003544924:web:864b36dc66b6f418fec999',
    messagingSenderId: '909003544924',
    projectId: 'danmaku-2772d',
    authDomain: 'danmaku-2772d.firebaseapp.com',
    storageBucket: 'danmaku-2772d.firebasestorage.app',
    measurementId: 'G-YP0VZ7CW7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGSyEz1OHcPvlmOhwHXYtXNf4skPr2AyM',
    appId: '1:909003544924:android:1bba459b62fb0053fec999',
    messagingSenderId: '909003544924',
    projectId: 'danmaku-2772d',
    storageBucket: 'danmaku-2772d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDBizuImII0HEZrWDW6k4bCXfZ4lHjAZo',
    appId: '1:909003544924:ios:790f894aaf43fecbfec999',
    messagingSenderId: '909003544924',
    projectId: 'danmaku-2772d',
    storageBucket: 'danmaku-2772d.firebasestorage.app',
    iosBundleId: 'com.example.danmakuUniverses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDBizuImII0HEZrWDW6k4bCXfZ4lHjAZo',
    appId: '1:909003544924:ios:790f894aaf43fecbfec999',
    messagingSenderId: '909003544924',
    projectId: 'danmaku-2772d',
    storageBucket: 'danmaku-2772d.firebasestorage.app',
    iosBundleId: 'com.example.danmakuUniverses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF4ymvTdp7B8Mq3J62i36dKsFgdlM2cpA',
    appId: '1:909003544924:web:cb9d63d9a6d94161fec999',
    messagingSenderId: '909003544924',
    projectId: 'danmaku-2772d',
    authDomain: 'danmaku-2772d.firebaseapp.com',
    storageBucket: 'danmaku-2772d.firebasestorage.app',
    measurementId: 'G-53EDBGPW9G',
  );
}